"""Word/phrase substitution maps for each compression level."""

# Level 1 is handled entirely by spaCy in caveman/nlp.py.

# ---------------------------------------------------------------------------
# Level 2 — tech abbreviations + action shortcuts
# ---------------------------------------------------------------------------

# Multi-word tech phrases (applied before single-word subs)
LEVEL2_PHRASES = [
    # AI / ML
    ("large language models", "LLMs"),
    ("large language model", "LLM"),
    ("natural language processing", "NLP"),
    ("artificial intelligence", "AI"),
    ("machine learning", "ML"),
    # Web / API
    ("application programming interface", "API"),
    ("user interface", "UI"),
    ("user experience", "UX"),
    ("message queue", "MQ"),
    ("key value", "KV"),
    # DevOps
    ("continuous deployment", "CD"),
    ("continuous delivery", "CD"),
    ("continuous integration", "CI"),
    # Existing
    ("regular expressions", "regexes"),
    ("regular expression", "regex"),
    ("pull requests", "PRs"),
    ("pull request", "PR"),
    ("command line", "CLI"),
    ("file system", "fs"),
    ("end to end", "e2e"),
]

# Single-word substitutions.
# Rules whose abbreviation costs MORE tokens than the original (o200k_base)
# have been removed (e.g. "functions"→"fns" is 1 tok→2 tok).
LEVEL2_SUBS = {
    # --- Data types ---
    "boolean": "bool",
    "booleans": "bools",
    "integer": "int",
    "integers": "ints",
    "number": "num",
    "numbers": "nums",
    "object": "obj",
    "objects": "objs",
    "string": "str",
    # --- Code constructs ---
    "argument": "arg",
    "arguments": "args",
    "attribute": "attr",
    "attributes": "attrs",
    "callback": "cb",
    "context": "ctx",
    "definition": "def",
    "definitions": "defs",
    "expression": "expr",
    "function": "fn",
    "implementation": "impl",
    "implementations": "impls",
    "iterator": "iter",
    "iterators": "iters",
    "parameter": "param",
    "parameters": "params",
    "pointer": "ptr",
    "pointers": "ptrs",
    "property": "prop",
    "properties": "props",
    "reference": "ref",
    "references": "refs",
    "structure": "struct",
    "template": "tmpl",
    "token": "tok",
    "value": "val",
    "values": "vals",
    "variable": "var",
    "variables": "vars",
    # --- Architecture ---
    "channel": "chan",
    "component": "comp",
    "container": "ctr",
    "controller": "ctrl",
    "dependency": "dep",
    "dependencies": "deps",
    "exception": "exc",
    "instance": "inst",
    "library": "lib",
    "libraries": "libs",
    "middleware": "mw",
    "module": "mod",
    "modules": "mods",
    "namespace": "ns",
    "package": "pkg",
    "processor": "proc",
    "service": "svc",
    "subscription": "sub",
    "subscriptions": "subs",
    # --- Infrastructure ---
    "address": "addr",
    "application": "app",
    "applications": "apps",
    "buffer": "buf",
    "configuration": "config",
    "configurations": "configs",
    "connection": "conn",
    "credential": "cred",
    "database": "db",
    "databases": "dbs",
    "deployment": "deploy",
    "deployments": "deploys",
    "destination": "dest",
    "directory": "dir",
    "directories": "dirs",
    "environment": "env",
    "environments": "envs",
    "infrastructure": "infra",
    "memory": "mem",
    "metadata": "meta",
    "migration": "mig",
    "migrations": "migs",
    "notification": "notif",
    "operation": "op",
    "operations": "ops",
    "permission": "perm",
    "pipeline": "pipe",
    "pipelines": "pipes",
    "repository": "repo",
    "repositories": "repos",
    "source": "src",
    "temporary": "tmp",
    "transaction": "tx",
    "version": "ver",
    "versions": "vers",
    # --- ML / AI ---
    "embedding": "emb",
    "embeddings": "embs",
    "evaluation": "eval",
    "gradient": "grad",
    "gradients": "grads",
    "hyperparameter": "hparam",
    "hyperparameters": "hparams",
    "inference": "infer",
    "prediction": "pred",
    "predictions": "preds",
    "vector": "vec",
    # --- Descriptors ---
    "administrator": "admin",
    "asynchronous": "async",
    "authentication": "auth",
    "collection": "coll",
    "command": "cmd",
    "development": "dev",
    "document": "doc",
    "documents": "docs",
    "error": "err",
    "errors": "errs",
    "format": "fmt",
    "information": "info",
    "maximum": "max",
    "minimum": "min",
    "message": "msg",
    "messages": "msgs",
    "original": "orig",
    "password": "pwd",
    "performance": "perf",
    "previous": "prev",
    "production": "prod",
    "request": "req",
    "response": "resp",
    "specification": "spec",
    "specifications": "specs",
    "synchronous": "sync",
    # --- Symbols ---
    "returns": "->",
    # --- Action shortcuts ---
    "aggregate": "agg",
    "aggregation": "agg",
    "aggregations": "aggs",
    "build": "make",
    "create": "make",
    "decode": "dec",
    "delete": "del",
    "describe": "desc",
    "encode": "enc",
    "execute": "exec",
    "generate": "gen",
    "implement": "impl",
    "initialization": "init",
    "initialize": "init",
    "obtain": "get",
    "optimize": "opt",
    "remove": "rm",
    "retrieve": "get",
    "serialize": "ser",
    "update": "upd",
    "using": "use",
    "utilize": "use",
    "validate": "valid",
    "write": "make",
}

# Level 2 phrase simplifications and filler adverb removal are handled by
# spaCy Matcher patterns in caveman/nlp.py (lemma / POS–based matching).

# ---------------------------------------------------------------------------
# Level 3 — full caveman: aggressive stripping + symbolic shorthand
# ---------------------------------------------------------------------------

# Multi-word phrase replacements (compressor sorts longest-first)
LEVEL3_PHRASE_REPLACEMENTS = [
    # Comparisons / equality
    ("not equal to", "!="),
    ("greater than or equal", ">="),
    ("less than or equal", "<="),
    ("greater than", ">"),
    ("more than", ">"),
    ("less than", "<"),
    ("equal to", "="),
    # Logic / flow
    ("as long as", "while"),
    ("as soon as", "when"),
    ("as a result", "so"),
    ("in other words", "ie"),
    ("for instance", "eg"),
    ("for example", "eg"),
    ("such as", "eg"),
    ("in addition to", "+"),
    ("as well as", "+"),
    # State / status
    ("not working", "broken"),
    ("relies on", "needs"),
    ("depends on", "needs"),
    ("right now", "now"),
    ("at this point", "now"),
    # Existing
    ("take a look at", "check"),
    ("whether or not", "if"),
    ("different from", "!="),
    ("the same as", "="),
    ("be able to", "can"),
    ("in order to", "->"),
    ("instead of", "not"),
    ("similar to", "like"),
    ("a lot of", "many"),
    ("make sure", "ensure"),
    ("looking for", "find"),
    ("needs to", "must"),
    ("need to", "must"),
    ("have to", "must"),
    ("has to", "must"),
    ("due to", "bc"),
    ("look at", "check"),
    ("in case", "if"),
    ("at least", "min"),
    ("at most", "max"),
]

# Single-word replacements
LEVEL3_WORD_REPLACEMENTS = {
    # Connectors
    # NOTE: "without" → "w/o" removed — "w/o" costs 2 BPE tokens vs 1 for
    # "without", making the substitution counter-productive.
    "because": "bc",
    "however": "but",
    "although": "but",
    "therefore": "so",
    "otherwise": "else",
    "when": "if",
    "versus": "vs",
    # Caveman simplifications
    "issue": "bug",
    "problem": "bug",
    "deprecated": "old",
    "legacy": "old",
    "automatically": "auto",
    "optional": "opt",
    "important": "key",
    "correct": "ok",
    "incorrect": "bad",
    "invalid": "bad",
    "valid": "ok",
    "large": "big",
    "null": "nil",
    "undefined": "nil",
    # Negative contractions → caveman negation
    "don't": "no",
    "doesn't": "no",
    "didn't": "no",
    "can't": "no",
    "won't": "no",
    "shouldn't": "no",
    "wouldn't": "no",
    "couldn't": "no",
    "isn't": "not",
    "aren't": "not",
    "wasn't": "not",
    "weren't": "not",
}

# Filler words to remove at level 3 that aren't caught by POS-based removal.
# Determiners, auxiliaries, pronouns, and prepositions are handled by apply_level3_nlp.
# "that" (SCONJ as relative-clause marker) is not ADP/DET/PRON so must be listed here.
LEVEL3_REMOVALS = frozenset({
    "that",
    "also", "very", "really", "quite", "rather", "then",
    "currently", "actually",
    "certainly", "definitely", "completely", "entirely",
    "particularly", "specifically", "generally",
})
